import { Router } from 'express';
import { authMiddleware } from '../middleware/auth.js';
import { createTask, listTasks, updateTaskStatus, getTaskHistory, reassignTask, updateTask, deleteTask } from '../controllers/taskController.js';
const router = Router();
router.post('/', authMiddleware, createTask);
router.get('/', authMiddleware, listTasks);
router.put('/:id/status', authMiddleware, updateTaskStatus);
router.put('/:id/reassign', authMiddleware, reassignTask);
router.get('/:id/history', authMiddleware, getTaskHistory);
router.put('/:id', authMiddleware, updateTask);
router.delete("/:id", authMiddleware, deleteTask);
export default router;
